---
- name: Install uwsgi
  become: yes
  pip: name=uwsgi

- name: Create Folders
  shell: mkdir -p /home/{{ user }}/etc /home/{{ user }}/log/uwsgi

- name: uwsgi upload uwsgi.ini
  template: src=uwsgi.ini dest=/home/{{ user }}/etc/{{ project_name }}.ini
