---
- name: common-python - link python 2
  become: yes
  file:
    src: /usr/bin/python2.7
    dest: /usr/bin/python
    state: link

- name: common-python - install global packages
  become: yes
  pip: name={{ item.name }}
  with_items:
    - { name: ipython, version: 5.3.0 }
    - { name: python-memcached }

- name: common-python - update distutils
  become: yes
  raw: easy_install distribute
