---

- name: Install Celery
  pip: name=celery 

- name: Create log directory for celery
  file: path={{ application_log_dir }}/celery
    owner={{ application_user }}
    group={{ application_group }}
    mode=0700
    state=directory
  tags: celery