---
- name: django - create folders
  shell: mkdir -p backups etc log project project_assets/media project_assets/static src

- name: Clone Project
  become: yes
  git: repo={{ git_repo }}
       dest=/var/www/{{ project_name }}
       accept_hostkey=yes

- name: django - create project venv
  shell: source ~/.bash_profile && mkvirtualenv {{ venv_name }}
  args:
      executable: /bin/bash

- name: django - install project venv
  shell: source ~/.bash_profile && workon {{ venv_name }} && pip install -r {{ server_requirements_txt }}
  args:
      executable: /bin/bash